import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/global/header";
import StairTransition from "@/components/global/animations/stairtransition";
import PageTransition from "@/components/global/animations/pagetransition";
import QueryProvider from "@/provider/query-provider";

const fount = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata: Metadata = {
  title: "Portfolio Maldonado",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fount.className}>
        <Header />
        <StairTransition />
        <PageTransition>
          <QueryProvider>{children}</QueryProvider>
        </PageTransition>
      </body>
    </html>
  );
}
